<?php

/**
 * River Functions
 * 
 * Loads the river-init.php file
 * 
 * DO NOT EDIT THIS FILE
 *
 * @category    River 
 * @package     Main
 * @subpackage  Functions
 * @since       0.0.0
 * @author      CodeRiver Labs 
 * @license     http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link        http://coderiverlabs.com/
 * 
 */

require_once( dirname( __FILE__ ) . '/lib/river-init.php' );
